server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/seafood?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: seafood
    password: fys`372427166
    schema: classpath:db/schema_data_latest.sql

logging:
  level:
    root: info